# import

In [1]:
import pandas as pd
import numpy as np
from os.path import join
import functions
import warnings
import re
warnings.simplefilter("ignore")

# 병합하기

### 일반

In [28]:
# ################################
company = "대성"
최종조회일 = "251231"
데이터종류 = "입금"
# 파일 하나만 추가할 경우 파일명만(확장자x), 여러개일 경우 ""
fn_excel = "입금조회새창_250701~251231"
# ################################

pk = 데이터종류 + "키"
if 데이터종류 == "입금" : 
    최초조회일 = "160119" if company == "솔림" else "150824"
    deposit_dtype = functions.deposit_dtype
    기간칼럼명 = "입금일"
    pk = "입금키_계좌키"
    
elif 데이터종류 == "메모" : 
    최초조회일 = "930426" if company == "솔림" else "971213"
    deposit_dtype = functions.memo_dtype
    기간칼럼명 = "등록일자"

base_dir = r"D:\3.자산\전산 dataset"
path_excel = join(base_dir,company,"기간축적데이터", 데이터종류)
path_parquet = join(base_dir,company, "기간축적데이터", 데이터종류, "parquet")
fn_write = company + 데이터종류+"전체_" + 최초조회일 + "~" + 최종조회일 +".parquet"

In [29]:
# parquet 파일 읽기
path_parquet_이전기간전체파일 = functions.키워드로파일명찾기(path_parquet, 포함키워드=company+데이터종류+"전체", 여러파일허용=True, 전체경로=True)
if isinstance(path_parquet_이전기간전체파일, list) : # 파일 여러개
    df_ori = pd.read_parquet(path_parquet_이전기간전체파일[-1])
elif isinstance(path_parquet_이전기간전체파일, str) : # 파일 한 개
    df_ori = pd.read_parquet(path_parquet_이전기간전체파일)
else : # 파일 없음
    df_ori = pd.DataFrame(None)
if not df_ori.empty :
    print(f'df_ori(이전기간 parquet파일) 기간 : {df_ori[f"{기간칼럼명}"].min()}~{df_ori[f"{기간칼럼명}"].max()}')

# 엑셀 파일 읽기
if fn_excel =="":
    fnlist = functions.키워드로파일명찾기(path_excel, 포함키워드=데이터종류+"조회새창", 여러파일허용=True)
    df = pd.DataFrame(None)
    for fn in fnlist :
        print(f'{fn} 읽기 시작')
        df = pd.concat([df, pd.read_excel(fn, dtype=deposit_dtype)])
else : 
    fnlist = functions.키워드로파일명찾기(path_excel, fn_excel+".xlsx")
    df = pd.read_excel(fnlist, dtype=deposit_dtype)


# 공지메모의 등록일자 바로잡기 : 엑셀만 하면 됨
if 데이터종류 == "메모" : 
    mask = df["등록일자"].str.contains("★", na=False)
    df.loc[mask, "등록일자"] = (
        df.loc[mask, "등록일자"]
        .str.extract(r"(\d{4}-\d{2}-\d{2})")[0]
    )

print(f'df(엑셀파일) 기간 : {df[f"{기간칼럼명}"].min()}~{df[f"{기간칼럼명}"].max()}')

# 합치기
df_concat = pd.concat([df_ori, df])

print("df_concat(병합파일) 기간확인", df_concat[f"{기간칼럼명}"].min(), df_concat[f"{기간칼럼명}"].max())
print("병합후 건수", len(df_concat))

df_ori(이전기간 parquet파일) 기간 : 2015-08-24~2025-06-30
df(엑셀파일) 기간 : 2025-07-01~2025-12-31
df_concat(병합파일) 기간확인 2015-08-24 2025-12-31
병합후 건수 75759

In [30]:
# 중복확인
if 데이터종류 == "입금" :
    df_concat[pk] = df_concat['입금키'].astype(str) + "_" + df_concat['계좌키'].astype(str)
df_concat[df_concat.duplicated(subset=[pk], keep=False)]

Empty DataFrame
Columns: [채무자키, 채권구분, 매각사구분, 입금키, 계좌키, 고객입금일, 입금일, 입금합계, 채무상태, 담당자, 입금원금, 입금법비용, 입금미수이자, 입금연체이자, 입금정상이자, 연체일수, 적용이자율, 입금기타, 입금자, 입금자구분, 입금구분, 담당입금구분, 입금통계구분, 입금기간, 입금기간일, 입금은행, 입금계좌번호, 가상계좌은행, 가상계좌번호, 상대방입금은행, 입금메모, 입금비고, 계좌번호, 회수원금, 회수법비용, 회수미수이자, 회수연체이자, 회수기타, 회수합계, 현재원금, 현재법비용, 현재미수이자, 현재연체이자, 현재합계, 원가입금, 매출입금, 비용입금, 잡이익, 법조치키, 입금고정키, 등록파일, 등록일자, 등록유저, 수정일자, 수정유저, 입금순서, 취소여부, 종결일, 매각사, 담보제공처, 담보제공구분, 매입일, 컷오프일, 최초이자기준일, 주민번호인, 지점, 부서, 팀, 고객입금액, 채무자명, 타입금키, 타채무자키, 보증인키, 직접입력메모, 담당문자전송, 리파이낸싱, 입금수수료율, 매입사, 입금키_계좌키]
Index: []

[0 rows x 79 columns]

In [31]:
# parquet 저장 : 통합본 읽을 때 정렬 및 인덱스 전처리 안 함에 유의
functions.to_parquet(df_concat, join(path_parquet, fn_write))

### 나의사건

#### 나의 사건 전체 목록 만들기/읽기

In [ ]:
# ################################
company = "솔림"
지점 = "광주"
최종조회일 = "250831" # 월말 자산정리일 기준으로 작성, 아닌 경우 df_law 읽을 때 따로 날짜 지정해야
데이터종류 = "나의사건"
나의사건_dtype = str
# 파일 하나만 추가할 경우 파일명만(확장자x), 여러개일 경우 ""
fn_excel = None  # "" : 여러파일, "파일명" : 단일파일, None : 기존 parquet만 읽기
최초조회일 = "170802" if company == "솔림" else ""
# ################################
path_excel = join(base_dir,company,"기간축적데이터", 데이터종류)
path_parquet = join(base_dir,company, "기간축적데이터", 데이터종류, "parquet")
fn_write = company + 데이터종류+"전체_" + 최초조회일 + "~" + 최종조회일 +".parquet"


# parquet 파일 읽기
path_parquet_files = functions.키워드로파일명찾기(path_parquet, 포함키워드=company+데이터종류+"전체", 여러파일허용=True, 전체경로=True)
if isinstance(path_parquet_files, str) :
    path_parquet_fn = path_parquet_files
else :
    path_parquet_fn = path_parquet_files[-1]

try : 
    df_ori = pd.read_parquet(path_parquet_fn)
except : # 파일이 없는 경우
    df_ori = pd.DataFrame(None)

# 엑셀 파일 읽기
if fn_excel =="":
    df = pd.DataFrame(None)
    for 사건진행구분 in ["확정사건", "완료사건","진행사건"] : 
        
        fnlist = functions.키워드로파일명찾기(path_excel, 포함키워드=지점+" "+사건진행구분, 여러파일허용=True)
        
        if isinstance(fnlist, str) : # 파일이 한 건
            print(f'{fnlist} 읽기 시작')
            df_temp = pd.read_excel(fnlist, dtype=나의사건_dtype)
            df_temp["사건진행구분"] = 사건진행구분
            df = pd.concat([df, df_temp])
        else :
            for fn in fnlist :
                print(f'{fn} 읽기 시작')
                df_temp = pd.read_excel(fn, dtype=나의사건_dtype)
                df_temp["사건진행구분"] = 사건진행구분
                df = pd.concat([df, df_temp])
elif fn_excel == None :
    df = df_ori.copy()
else : 
    fnlist = functions.키워드로파일명찾기(path_excel, fn_excel+".xlsx")
    사건진행구분 = re.search("(진행|확정|완료)사건", "광주 확정사건 220701~250831")[0]
    df = pd.read_excel(fnlist, dtype=나의사건_dtype)
    df["사건진행구분"] = 사건진행구분

if fn_excel!=None :
    df["지점"] = 지점

#### 채무자키 매칭

In [ ]:
# 채무자키 넣기
    # 법조치 읽기
fn_law = functions.키워드로파일명찾기(join(base_dir,'솔림',최종조회일,"parquet"),"법조치조회새창", 여러파일허용=False)
df_law = pd.read_parquet(fn_law)
    # 개인회생 전체파일 읽기
fn_rehabilitation = functions.키워드로파일명찾기(join(base_dir,'솔림',최종조회일,"parquet"),r"\[상태DC\]개인회생", 여러파일허용=False)
df_rehabilitation = pd.read_parquet(fn_rehabilitation)

In [34]:
df_law.columns[df_law.columns.str.contains('주민')]

Index(['주민번호'], dtype='object')

In [ ]:
# 1. df_law 후보 만들기
change_cols_name_dict = {"관할법원":"법원", "관련사건법원":"법원", "관련법조치관할법원": "법원", "관련사건번호":"사건번호", "관련법조치사건번호":"사건번호", "주민번호":"차주주민번호", "주민번호인":"차주주민번호"}

cand1 = df_law[["관할법원", "사건번호", "채무자키","주민번호"]].rename(columns=change_cols_name_dict)
cand2 = df_law[["관련사건법원", "관련사건번호", "채무자키","주민번호"]].rename(columns=change_cols_name_dict)
cand3 = df_law[["관련법조치관할법원", "관련법조치사건번호", "채무자키","주민번호"]].rename(columns=change_cols_name_dict)

cand4 = df_rehabilitation[["관할법원","사건번호","채무자키","주민번호인"]].rename(columns=change_cols_name_dict)

# 2. 전부 합치기
df_law_candidates = pd.concat([cand1, cand2, cand3, cand4], ignore_index=True)


# 후처리 
    # 정렬
df_law_candidates = df_law_candidates.sort_values(['법원','사건번호','채무자키'])
    
    # 법원-사건번호-채무자키 중복건 삭제
df_law_candidates = df_law_candidates.drop_duplicates(subset=['법원','사건번호','채무자키'], keep='first')

    # 관할법원, 사건번호 없는 건은 삭제
df_law_candidates = df_law_candidates.replace("", np.nan)
print('법원사건번호에 빈값 있는 행:',len(df_law_candidates))
df_law_candidates = df_law_candidates.dropna(subset=["법원", "사건번호"], how='any')
print('빈값 삭제 후',len(df_law_candidates))

# [dc] 동일 사건에, 차주 주민번호 다른 건 확인
dup_cases = (
    df_law_candidates
    .groupby(["법원", "사건번호"])["차주주민번호"]
    .nunique()
    .reset_index()
    .query("차주주민번호 > 1")   # 고유 주민번호 개수가 2개 이상인 경우만
)

    # 중복등록이 맞음
if company == "솔림" : 
    data = [
        ["광주지방법원","2003가단16998"],
        
    ]
    중복확인된사건 = pd.DataFrame(data, columns=["법원","사건번호"])



# 해당 케이스의 원본 데이터 뽑기
problem_rows = df_law_candidates.merge(dup_cases[["법원","사건번호"]], on=["법원","사건번호"], how="inner")
functions.save_excel_with_explain(problem_rows, "차주중복등록사건.xlsx", key_columns_no=2)

법원사건번호에 빈값 있는 행: 172322
빈값 삭제 후 130451
★ 차주중복등록사건 252건 엑셀출력

In [60]:
pd.DataFrame([["광주지방법원","2003가단16998"]], columns=["법원","사건번호"])

       법원         사건번호
0  광주지방법원  2003가단16998

In [ ]:
# # 3. 중복제거: 법원+사건번호 기준, 채무자키는 첫 번째만
# df_law_candidates = df_law_candidates.drop_duplicates(subset=["법원","사건번호"])

# # 4. df와 merge
# df = df.merge(df_law_candidates, on=["법원","사건번호"], how="left")

# # 5. 못 찾은 건 빈 문자열
# df["채무자키"] = df["채무자키"].fillna("")

         법원          사건번호      채무자키          차주주민번호
0    수원지방법원  2025타채134613  20428861  401108-1052413
1    수원지방법원  2025타채134613  20500063  821210-1122013
2    광주지방법원    2024하면5081  20428934  640311-1495617
3    광주지방법원    2024하면5081  20429840  571115-2495634
4    전주지방법원     2024하면296  20413618  640522-2661011
..      ...           ...       ...             ...
426  울산지방법원   2019개회11603  20514978  730209-2785414
427  울산지방법원   2019개회11597  20515427  710428-1453110
428  울산지방법원   2019개회11597  20514978  730209-2785414
429  수원회생법원   2019개회16391  20408300  681020-2668033
430  수원회생법원   2019개회16391  20416866  630702-2106328

[431 rows x 4 columns]

In [ ]:
# # 엑셀에 저장
# with pd.ExcelWriter(path_excel, engine='openpyxl', mode = 'a', if_sheet_exists = 'replace') as writer:
#     df.to_excel(writer, sheet_name = "집행문", index=False)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [50]:
# 합치기
df_concat = pd.concat([df_ori, df])

# 불요칼럼 삭제, 정렬->중복검사
    # 불요칼럼
불요칼럼 = ["번호"]
df_concat = df_concat.drop(columns=불요칼럼)

df_concat["법원"] = df_concat.법원.str.replace("지법", "지방법원")

    # 정렬 : 최근 사건이 먼저, 확정사건이 먼저 (확정사건을 추가한 경우 진행사건이 삭제될 수 있도록)
df_concat["접수일자"] = pd.to_datetime(df_concat["접수일자"], errors='coerce')
df_concat["확정일자"] = pd.to_datetime(df_concat["확정일자"], errors='coerce')
df_concat = df_concat.sort_values(by=["확정일자", "접수일자", "법원","사건번호"], ascending=[False, False, True,True])

    # 중복확인 및 삭제
functions.display_with_explain(df_concat[df_concat.duplicated(subset=["법원", "사건번호"], keep=False)], "중복사건")
df_concat = df_concat.drop_duplicates(subset=["법원", "사건번호"])

    # 새로운 인덱싱
df_concat.reset_index(inplace=True, drop=True)

    # 칼럼순서
cols = ['지점', '법원', '사건번호', '재판부', '사건지위', '원고', '피고', '사건진행구분','확정일자', '접수일자',
       '기일시간', '기일장소']
df_concat = df_concat[cols]

# parquet 저장 : 통합본 읽을 때 정렬 및 인덱스 전처리 안 함에 유의
functions.to_parquet(df_concat, join(path_parquet, fn_write))

☆ 중복사건 없음

# 읽기

In [3]:
#########################
company = "솔림"
데이터종류 = "입금"
#########################
base_dir = r"D:\3.자산\전산 dataset"
path_parquet = join(base_dir,company,"기간축적데이터", 데이터종류, "parquet")
fnlist = functions.키워드로파일명찾기(path_parquet, 포함키워드=company+데이터종류+"전체", 여러파일허용=True, 전체경로=True)
if isinstance(fnlist, str) :
    fn = fnlist
else :
    fn = fnlist[-1]
df = pd.read_parquet(fn)

In [4]:
df.columns

Index(['채무자키', '채권구분', '매각사구분', '입금키', '계좌키', '고객입금일', '입금일', '입금합계', '채무상태',
       '담당자', '입금원금', '입금법비용', '입금미수이자', '입금연체이자', '입금정상이자', '연체일수', '적용이자율',
       '입금기타', '입금자', '입금자구분', '입금구분', '담당입금구분', '입금통계구분', '입금기간', '입금기간일',
       '입금은행', '입금계좌번호', '가상계좌은행', '가상계좌번호', '상대방입금은행', '입금메모', '입금비고', '계좌번호',
       '회수원금', '회수법비용', '회수미수이자', '회수연체이자', '회수기타', '회수합계', '현재원금', '현재법비용',
       '현재미수이자', '현재연체이자', '현재합계', '원가입금', '매출입금', '비용입금', '잡이익', '법조치키',
       '입금고정키', '등록파일', '등록일자', '등록유저', '수정일자', '수정유저', '입금순서', '취소여부', '종결일',
       '매각사', '담보제공처', '담보제공구분', '매입일', '컷오프일', '최초이자기준일', '주민번호인', '지점', '부서',
       '팀', '고객입금액', '채무자명', '타입금키', '타채무자키', '보증인키', '직접입력메모', '담당문자전송',
       '리파이낸싱', '입금수수료율', '매입사', '입금키_계좌키'],
      dtype='object')

In [5]:
df.입금기간.unique()

array(['매입전', 'nan', '원상회복전', '매각사측', '\x7f', '환불', '회수제외', '매각후',
       '2022-08-25', '환매'], dtype=object)

In [11]:
df[(df.입금기간=='2022-08-25')][["채무자키","입금키","입금합계","입금구분","입금기간"]].to_excel("입금기간_20220825_내역.xlsx", index=False)

In [40]:
# 1. 원상회복전 마지막 입금일 계산
last_restore = (
    df[df["입금기간"] == "원상회복전"]
    .groupby("주민번호인")["입금일"]
    .max()
    .rename("원상회복전_마지막입금일")
)

# 2. 원본 df에 조인
df2 = df.merge(last_restore, on="주민번호인", how="left")

# 3. 조건 필터링
cond = (
    df2["원상회복전_마지막입금일"].notna() &             # 원상회복전 존재
    (df2["입금일"] < df2["원상회복전_마지막입금일"]) &    # 그 이전 입금
    (df2["입금일"] < df2["최초이자기준일"]) &              # 최초이자기준일 이전 입금
    (df2["입금기간"] == "")                               # 입금기간 공란
)

result = df2[cond]

In [41]:
result = result[result.입금구분 != "부채증명서"]
result

,채무자키,채권구분,매각사구분,입금키,계좌키,고객입금일,입금일,입금합계,채무상태,담당자,...,채무자명,타입금키,타채무자키,보증인키,직접입력메모,담당문자전송,리파이낸싱,입금수수료율,매입사,원상회복전_마지막입금일
330262,20428578,NPL,케이에스,30807784,200948174,nan,2023-07-20,200000,약정(확정),정호석,...,정상빈,nan,9009000070,NaN,nan,nan,nan,0,NaN,2023-09-05
346951,20428578,NPL,케이에스,30713749,200948174,nan,2023-06-20,200000,약정(확정),정호석,...,정상빈,nan,9009000070,NaN,nan,nan,nan,0,NaN,2023-09-05
365648,20428578,NPL,케이에스,30610134,200948174,nan,2023-05-19,200000,약정(확정),정호석,...,정상빈,nan,9009000070,NaN,nan,nan,nan,0,NaN,2023-09-05
383721,20428578,NPL,케이에스,30512738,200948174,nan,2023-04-20,200000,약정(확정),정호석,...,정상빈,nan,9009000070,NaN,nan,nan,nan,0,NaN,2023-09-05
403636,20428578,NPL,케이에스,30435582,200948174,nan,2023-03-20,200000,약정(확정),정호석,...,정상빈,nan,9009000070,NaN,nan,nan,nan,0,NaN,2023-09-05
410070,20413785,NPL,한울가람,30417780,200922028,nan,2023-03-06,231894,정상,조창익,...,강현주,nan,1803000084,NaN,nan,nan,nan,0,NaN,2025-05-19
420540,20428578,NPL,케이에스,30385712,200948174,nan,2023-02-20,200000,약정(확정),정호석,...,정상빈,nan,9009000070,NaN,nan,nan,nan,0,NaN,2023-09-05
440404,20428578,NPL,케이에스,30327597,200948174,nan,2023-01-20,200000,약정(확정),정호석,...,정상빈,nan,9009000070,NaN,nan,nan,nan,0,NaN,2023-09-05
459845,20428578,NPL,케이에스,30272437,200948174,nan,2022-12-20,200000,약정(확정),한웅희,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
481670,20428578,NPL,케이에스,30211262,200948174,nan,2022-11-18,200000,약정(확정),한웅희,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
502695,20428578,NPL,케이에스,29996536,200948174,nan,2022-10-20,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
521713,20428578,NPL,케이에스,29938340,200948174,nan,2022-09-20,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
542567,20428578,NPL,케이에스,29894490,200948174,nan,2022-08-19,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
562868,20428578,NPL,케이에스,29848487,200948174,nan,2022-07-20,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
583747,20428578,NPL,케이에스,29383377,200948174,nan,2022-06-20,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
601709,20428578,NPL,케이에스,29337442,200948174,nan,2022-05-20,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
619844,20428578,NPL,케이에스,29127904,200948174,nan,2022-04-20,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
637336,20428578,NPL,케이에스,29080151,200948174,nan,2022-03-19,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
651031,20428578,NPL,케이에스,29018502,200948174,2022-02-22,2022-02-25,200000,약정(확정),정재하,...,정상빈,nan,9009000070,NaN,nan,Y,nan,0,NaN,2023-09-05
750340,20413785,NPL,한울가람,32612000,200922028,nan,2024-12-24,12863,정상,권영진,...,강현주,nan,1803000084,NaN,nan,nan,농협(비아)-13,0,NaN,2025-05-19
751098,20413785,NPL,한울가람,32606939,200922028,nan,2024-12-24,2068,정상,권영진,...,강현주,nan,1803000084,NaN,nan,nan,농협(비아)-13,0,NaN,2025-05-19

In [42]:
result = result.drop_duplicates(subset=["채무자키"], keep='first')
result

,채무자키,채권구분,매각사구분,입금키,계좌키,고객입금일,입금일,입금합계,채무상태,담당자,...,채무자명,타입금키,타채무자키,보증인키,직접입력메모,담당문자전송,리파이낸싱,입금수수료율,매입사,원상회복전_마지막입금일
330262,20428578,NPL,케이에스,30807784,200948174,nan,2023-07-20,200000,약정(확정),정호석,...,정상빈,nan,9009000070,NaN,nan,nan,nan,0,NaN,2023-09-05
410070,20413785,NPL,한울가람,30417780,200922028,nan,2023-03-06,231894,정상,조창익,...,강현주,nan,1803000084,NaN,nan,nan,nan,0,NaN,2025-05-19

In [34]:
result.columns[result.columns.str.contains('이자')]

Index(['입금미수이자', '입금연체이자', '입금정상이자', '적용이자율', '회수미수이자', '회수연체이자', '현재미수이자',
       '현재연체이자', '최초이자기준일'],
      dtype='object')